FISH_MASTER_DATA = {
  "fish_list": [
    {
      "id": 1,
      "level": "一星",
      "name": "塑膠袋",
      "min_size_m": 0.05,
      "max_size_m": 0.4,
      "min_weight_kg": 0.001,
      "max_weight_kg": 0.01,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "隨著水流飄盪的塑膠袋，遠看像是一隻水母，不少新手釣客都曾被它騙過，連海龜也不例外"
    },
    {
      "id": 2,
      "level": "一星",
      "name": "可樂罐",
      "min_size_m": 0.1,
      "max_size_m": 0.15,
      "min_weight_kg": 0.02,
      "max_weight_kg": 0.05,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "不知道在海中漂流了多久，鋁罐身上的圖案早已模糊不清，只剩下歲月留下的刮痕。"
    },
    {
      "id": 3,
      "level": "一星",
      "name": "鞋子",
      "min_size_m": 0.2,
      "max_size_m": 0.35,
      "min_weight_kg": 0.15,
      "max_weight_kg": 0.5,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "單獨出現的鞋子總讓人好奇它失去另一半的原因，但大多數時候只是個無解的謎團。"
    },
    {
      "id": 4,
      "level": "一星",
      "name": "指南針",
      "min_size_m": 0.05,
      "max_size_m": 0.12,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.08,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "雖然已經進水損壞，但指針仍會微微轉動，彷彿想為迷失的旅人指出方向。"
    },
    {
      "id": 5,
      "level": "一星",
      "name": "生鏽鐵管",
      "min_size_m": 0.3,
      "max_size_m": 0.8,
      "min_weight_kg": 0.8,
      "max_weight_kg": 3.5,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "長年浸泡在水中的鐵管佈滿鏽蝕，有時甚至會成為小型魚類暫時的棲身之處。"
    },
    {
      "id": 6,
      "level": "一星",
      "name": "零食包裝袋",
      "min_size_m": 0.08,
      "max_size_m": 0.25,
      "min_weight_kg": 0.001,
      "max_weight_kg": 0.005,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "色彩鮮豔的包裝袋在水中格外顯眼，仔細一看還有樂事的logo圖案"
    },
    {
      "id": 7,
      "level": "一星",
      "name": "輪胎",
      "min_size_m": 0.4,
      "max_size_m": 0.8,
      "min_weight_kg": 2.0,
      "max_weight_kg": 8.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "沉重的廢棄輪胎意外成了人工礁石，偶爾能看見小魚藏在其中。"
    },
    {
      "id": 101,
      "level": "二星",
      "name": "火之吻",
      "min_size_m": 0.1,
      "max_size_m": 0.25,
      "min_weight_kg": 0.04,
      "max_weight_kg": 0.06,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "在釣起的那一刻，身上仍在冒著火光，不過有些神奇是他並不會燃燒漫延，也沒有溫度，所以儘管在水中也能散發著光芒照亮四周"
    },
    {
      "id": 102,
      "level": "二星",
      "name": "翡翠條紋雕",
      "min_size_m": 0.1,
      "max_size_m": 0.2,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.05,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "有著明顯綠色的外觀，仔細一看上面還有細小有如礦石紋路，不過一旦死亡身體潰爛也就失去其特徵了。"
    },
    {
      "id": 103,
      "level": "二星",
      "name": "河豚",
      "min_size_m": 0.2,
      "max_size_m": 0.7,
      "min_weight_kg": 0.3,
      "max_weight_kg": 0.9,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "外觀和沙土相近，常生存在河床附近，奇特的外觀也被釣魚客稱為「沙灘隱士」。"
    },
    {
      "id": 104,
      "level": "二星",
      "name": "海馬",
      "min_size_m": 0.01,
      "max_size_m": 0.15,
      "min_weight_kg": 0.001,
      "max_weight_kg": 0.15,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "頭部像馬，身體表面沒有鱗片，而是由骨板形成堅硬外殼，不過體重卻意外地輕。"
    },
    {
      "id": 105,
      "level": "二星",
      "name": "泡泡大師",
      "min_size_m": 0.05,
      "max_size_m": 0.3,
      "min_weight_kg": 0.01,
      "max_weight_kg": 0.03,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "身體幾乎透明，只能從泡泡反射出的微光看見輪廓。遇到危險時，牠會製造大量泡泡迷惑敵人，因此被稱為「泡泡大師」。"
    },
    {
      "id": 106,
      "level": "二星",
      "name": "泡泡眼",
      "min_size_m": 0.05,
      "max_size_m": 0.15,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.15,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "擁有遠超身體比例的圓滾滾大眼睛，外表呈現鮮豔的橘色，傳聞牠能透過眼睛看見水流中的細微變化，因此很少被掠食者偷襲成功。"
    },
    {
      "id": 107,
      "level": "二星",
      "name": "星雲漫步者",
      "min_size_m": 0.05,
      "max_size_m": 0.15,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.15,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "一種神秘的小魚，魚鱗表面閃爍著如銀河般的星光紋路，夜晚時牠會散發淡淡光輝，在水中留下宛如星雲漂流的軌跡。"
    },
    {
      "id": 108,
      "level": "二星",
      "name": "招潮蟹",
      "min_size_m": 0.02,
      "max_size_m": 0.05,
      "min_weight_kg": 0.01,
      "max_weight_kg": 0.04,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "一群小型海岸蟹類的統稱，因雄蟹會揮舞特大蟹螯，像在「招手」或「招潮」而得名。"
    },
    {
      "id": 109,
      "level": "二星",
      "name": "紫色條紋魚",
      "min_size_m": 0.1,
      "max_size_m": 0.2,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.09,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "有著明顯紫色外觀，仔細一看發現還真的是一隻很普通的魚。"
    },
    {
      "id": 110,
      "level": "二星",
      "name": "神仙魚",
      "min_size_m": 0.15,
      "max_size_m": 0.3,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.06,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "修長的身軀搭配巨大的魚鰭，讓牠看起來比實際體型更加高大優雅，被稱為「深海貴族」。"
    },
    {
      "id": 111,
      "level": "二星",
      "name": "紫電突擊兵",
      "min_size_m": 0.1,
      "max_size_m": 0.2,
      "min_weight_kg": 0.05,
      "max_weight_kg": 0.1,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "擁有銳利兇狠的眼神與佈滿尖牙的大嘴，任何靠近的生物都會感受到強烈壓迫感。頭頂兩根堅硬的外骨猶如戰士的長角，紫色身影會如閃電般劃過水域。"
    },
    {
      "id": 112,
      "level": "二星",
      "name": "聖光水母",
      "min_size_m": 0.1,
      "max_size_m": 0.4,
      "min_weight_kg": 0.5,
      "max_weight_kg": 2.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "沒有大腦、骨骼、心臟的一種水母，依靠神經網路感知周遭世界，顏色相當漂亮，有如一盞吊燈在水中漂著。"
    },
    {
      "id": 113,
      "level": "二星",
      "name": "小藍綠寶石",
      "min_size_m": 0.1,
      "max_size_m": 0.2,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.09,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "藍綠色的外觀有如寶石般的配色，不過其實看起來卻沒什麼質感。"
    },
    {
      "id": 114,
      "level": "二星",
      "name": "小丑魚",
      "min_size_m": 0.05,
      "max_size_m": 0.1,
      "min_weight_kg": 0.01,
      "max_weight_kg": 0.04,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "棲息於溫暖海域的珊瑚礁附近，與海葵形成特殊共生關係，是最具代表性的熱帶觀賞魚之一。"
    },
    {
      "id": 115,
      "level": "二星",
      "name": "琥珀守護者",
      "min_size_m": 0.1,
      "max_size_m": 0.2,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.09,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "體型嬌小但性格穩定，據說會圍繞領域形成微弱守護場，驅離小型掠食者。"
    },
    {
      "id": 201,
      "level": "三星",
      "name": "天才機械魚",
      "min_size_m": 0.02,
      "max_size_m": 0.15,
      "min_weight_kg": 0.01,
      "max_weight_kg": 0.2,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "疑似人造生物兵器殘留體，全身以機械結構替代生物組織，仍維持基本生命活動跡象。"
    },
    {
      "id": 202,
      "level": "三星",
      "name": "深海探險家",
      "min_size_m": 0.1,
      "max_size_m": 0.2,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.09,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "深海中變異的燈籠魚個體，體表呈深綠色幽光，發光器官會隨游動節奏微弱閃爍。"
    },
    {
      "id": 203,
      "level": "三星",
      "name": "冰晶魚",
      "min_size_m": 0.05,
      "max_size_m": 0.1,
      "min_weight_kg": 0.01,
      "max_weight_kg": 0.04,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "棲息於極寒水域的小型魚種，體表覆蓋類似冰晶的透明鱗片，游動時會在水中留下細微的霜白光痕。"
    },
    {
      "id": 204,
      "level": "三星",
      "name": "祈願小金",
      "min_size_m": 0.05,
      "max_size_m": 0.1,
      "min_weight_kg": 0.01,
      "max_weight_kg": 0.04,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "體色如金色微光般閃耀的微型魚種，據說在水中閃爍時能讓人產生願望實現的錯覺，因此被視為幸運象徵。"
    },
    {
      "id": 205,
      "level": "三星",
      "name": "憂鬱小藍",
      "min_size_m": 0.05,
      "max_size_m": 0.1,
      "min_weight_kg": 0.01,
      "max_weight_kg": 0.04,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "通體呈深藍色的安靜魚種，常緩慢獨游於水層之間，情緒般的色澤連小編看了都憂鬱。"
    },
    {
      "id": 206,
      "level": "三星",
      "name": "虛空漫遊者",
      "min_size_m": 0.15,
      "max_size_m": 0.3,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.06,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "在深海裂隙附近被發現的異常魚種，身體邊緣呈現不穩定的黑色扭曲感，彷彿不完全存在於現實之中。"
    },
    {
      "id": 207,
      "level": "三星",
      "name": "晶藍棘刺魚",
      "min_size_m": 0.1,
      "max_size_m": 0.2,
      "min_weight_kg": 0.03,
      "max_weight_kg": 0.09,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "據記載生活於富含礦物質的海域，不過卻沒有演化出晶化結構，但仍有小顆晶體附著於身上"
    },
    {
      "id": 208,
      "level": "三星",
      "name": "新手小鰷魚",
      "min_size_m": 0.05,
      "max_size_m": 0.1,
      "min_weight_kg": 0.01,
      "max_weight_kg": 0.04,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "誕生在新手村的雜魚種，體型細小動作也有些笨拙，沒什麼價值不過當作練習素材是個不錯的選擇"
    },
    {
      "id": 209,
      "level": "三星",
      "name": "旗魚",
      "min_size_m": 1.5,
      "max_size_m": 3.0,
      "min_weight_kg": 20.0,
      "max_weight_kg": 100.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "熱帶海域的掠食性魚類，長長的鼻子是牠最大的特徵，身體呈流線型，以游泳速度快而聞名，體色為深藍色，身側有淡色條紋。"
    },
    {
      "id": 210,
      "level": "三星",
      "name": "粉紅銀河夢",
      "min_size_m": 1.0,
      "max_size_m": 4.0,
      "min_weight_kg": 20.0,
      "max_weight_kg": 70.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "喜歡在月光下躍出海面，把尾鰭灑出的水花變成一串流星。雖然沒人知道那些星光從何而來，但大家都認為那是牠送出的祝福。"
    },
    {
      "id": 211,
      "level": "三星",
      "name": "深海突襲者",
      "min_size_m": 2.0,
      "max_size_m": 3.8,
      "min_weight_kg": 40.0,
      "max_weight_kg": 80.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "據說牠游過的海域總會伴隨微弱電流，因此常被誤認為是移動中的暴風眼。雖然外表兇猛，但其實最喜歡追逐發光的小魚玩耍。"
    },
    {
      "id": 212,
      "level": "三星",
      "name": "章魚",
      "min_size_m": 0.5,
      "max_size_m": 1.0,
      "min_weight_kg": 1.0,
      "max_weight_kg": 10.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "一種高智商的海洋無脊椎動物，身體柔軟，能鑽過非常狹小的縫隙，據說擁有 3 顆心臟，比不過貓咪的 9 條命就是了。"
    },
    {
      "id": 213,
      "level": "三星",
      "name": "烏賊",
      "min_size_m": 0.15,
      "max_size_m": 0.4,
      "min_weight_kg": 0.5,
      "max_weight_kg": 3.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "具有相當多條的手臂，有 8 條腕和 2 條較長的觸腕，還有發達的眼睛，視力極佳，似乎比你還有作用。"
    },
    {
      "id": 214,
      "level": "三星",
      "name": "軟軟沙灘魟",
      "min_size_m": 0.3,
      "max_size_m": 0.7,
      "min_weight_kg": 1.0,
      "max_weight_kg": 15.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "身體非常扁平，體型大卻沒什麼重量，尾巴看似鞭子不過這隻卻沒有毒性（只是牠沒毒而已誒）。"
    },
    {
      "id": 215,
      "level": "三星",
      "name": "熔岩巨鯊",
      "min_size_m": 1.2,
      "max_size_m": 1.8,
      "min_weight_kg": 10.0,
      "max_weight_kg": 25.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "具有較高的體溫，連靠近牠都會感受到溫暖，據釣魚佬所述，牠的每一口食物都散發著焦香味。"
    },
    {
      "id": 301,
      "level": "四星",
      "name": "數碼螢光雕",
      "min_size_m": 0.2,
      "max_size_m": 0.5,
      "min_weight_kg": 0.2,
      "max_weight_kg": 3.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "數碼螢光雕是一種帶有未來科技感的鯛魚。魚鱗表面呈現數位像素般的光澤，在黑暗水域中會散發柔和的電子螢光。"
    },
    {
      "id": 302,
      "level": "四星",
      "name": "秘寶紫鱗",
      "min_size_m": 0.1,
      "max_size_m": 0.3,
      "min_weight_kg": 0.5,
      "max_weight_kg": 5.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "因長期生活於富含礦物質的海域，鱗片與紫水晶融合共生，形成獨特的晶化外觀。"
    },
    {
      "id": 303,
      "level": "四星",
      "name": "寶箱守護者",
      "min_size_m": 0.2,
      "max_size_m": 0.5,
      "min_weight_kg": 0.7,
      "max_weight_kg": 2.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "以沉船寶箱為巢穴的異變魚種，外殼與魚體融合，會對靠近寶物的生物展開警戒行動。"
    },
    {
      "id": 304,
      "level": "四星",
      "name": "幻彩水晶魚",
      "min_size_m": 0.1,
      "max_size_m": 0.3,
      "min_weight_kg": 0.5,
      "max_weight_kg": 5.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "因長期生活於富含礦物質的海域，鱗片與藍水晶融合共生，形成獨特的晶化外觀。"
    },
    {
      "id": 305,
      "level": "四星",
      "name": "海洋守護者",
      "min_size_m": 0.05,
      "max_size_m": 0.3,
      "min_weight_kg": 0.3,
      "max_weight_kg": 1.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "不知道去哪裡撿來的劍和盾，有如士兵一樣會保護自己的領域，遇到侵略者會集體拿起武器反抗。"
    },
    {
      "id": 306,
      "level": "四星",
      "name": "吳郭魚",
      "min_size_m": 0.2,
      "max_size_m": 0.5,
      "min_weight_kg": 0.5,
      "max_weight_kg": 3.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "適應力極強的淡水魚，無論是池塘、河川還是水庫都能發現牠的蹤影。雖然外表樸實無華，卻憑藉一己之力弄髒全身"
    },
    {
      "id": 307,
      "level": "四星",
      "name": "獅子魚",
      "min_size_m": 0.2,
      "max_size_m": 0.4,
      "min_weight_kg": 0.5,
      "max_weight_kg": 1.5,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "外觀具有鮮艷的條紋和豐富䟍色，看似優美不過身上的毒刺卻向大多數追求者表示拒絕。"
    },
    {
      "id": 308,
      "level": "四星",
      "name": "衝浪飛魚",
      "min_size_m": 0.3,
      "max_size_m": 0.8,
      "min_weight_kg": 0.3,
      "max_weight_kg": 1.2,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "每天都在練習空中衝浪的魚，夢想是參加海洋極限運動大賽。雖然常常落水，但牠們從不缺席下一道浪。"
    },
    {
      "id": 309,
      "level": "四星",
      "name": "時光鯨",
      "min_size_m": 3.0,
      "max_size_m": 5.0,
      "min_weight_kg": 3000.0,
      "max_weight_kg": 10000.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "在陽光的照耀下，身體散發著有如銀河星空的顏色，被釣魚客譽為夢幻的魚種。"
    },
    {
      "id": 310,
      "level": "四星",
      "name": "深淵蒼龍",
      "min_size_m": 2.0,
      "max_size_m": 8.0,
      "min_weight_kg": 2000.0,
      "max_weight_kg": 7000.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "據說牠在海霧最濃的清晨現身，蜿蜒的身影常被誤認為漂浮的海流。雖然外表威風凜凜，但其實很喜歡把閃亮的貝殼偷偷藏進自己的巢穴。"
    },
    {
      "id": 311,
      "level": "四星",
      "name": "巨大水豚魚",
      "min_size_m": 2.0,
      "max_size_m": 3.0,
      "min_weight_kg": 50.0,
      "max_weight_kg": 70.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "沉著冷靜的水豚君，不知為何長出了魚鰭與尾巴。無論被釣上岸還是在水中悠游，總是一副與世無爭的模樣，還能頂著一顆蘋果。"
    },
    {
      "id": 312,
      "level": "四星",
      "name": "時空裂縫鯊",
      "min_size_m": 3.0,
      "max_size_m": 7.0,
      "min_weight_kg": 8.0,
      "max_weight_kg": 50.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "在大學時代被代碼蹂躪過後，身體逐漸發生異變，牠的身旁時常出現不穩定的時空裂縫，連牠自己也不知道下一秒會游到哪個年代。"
    },
    {
      "id": 313,
      "level": "四星",
      "name": "櫻花鉤吻鮭",
      "min_size_m": 0.2,
      "max_size_m": 0.5,
      "min_weight_kg": 0.2,
      "max_weight_kg": 1.5,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "棲息於高山雲霧間溪流的珍稀魚類，身上的斑點猶如飄落水中的櫻花。據說只有最純淨的溪水，才能映照出牠優雅游動的身影。"
    },
    {
      "id": 314,
      "level": "四星",
      "name": "盲眼巨蟲",
      "min_size_m": 1.0,
      "max_size_m": 4.0,
      "min_weight_kg": 3.0,
      "max_weight_kg": 9.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "長年棲息於深海裂谷，雙眼早已退化，不過能透過水流和空氣的細微震震感知周遭環境，據說任何靠近牠領地的生物都難以逃過牠的察覺。"
    },
    {
      "id": 315,
      "level": "四星",
      "name": "封包食人魚",
      "min_size_m": 0.05,
      "max_size_m": 0.2,
      "min_weight_kg": 0.1,
      "max_weight_kg": 0.5,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "棲息於資料海的深層節點，專門撕裂與吞噬封包。牠們成群移動時會形成恐怖的資料風暴，任何未加密的訊息都會在瞬間被拆解殆盡。"
    },
    {
      "id": 401,
      "level": "五星",
      "name": "寶石海龜",
      "min_size_m": 1.0,
      "max_size_m": 6.0,
      "min_weight_kg": 10.0,
      "max_weight_kg": 40.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "傳說中背負著海底礦脈誕生的古老生物，龜甲並非骨骼，而是由無數結晶寶石構成。每當牠緩慢移動時，海底便會閃爍出彩虹般的光輝。"
    },
    {
      "id": 402,
      "level": "五星",
      "name": "像素海龍王",
      "min_size_m": 7.0,
      "max_size_m": 20.0,
      "min_weight_kg": 3000.0,
      "max_weight_kg": 10000.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "傳說牠是由無數海洋記憶凝聚而成的古老王者。每當牠從深海升起，海面便會泛起七彩波紋，吸引無數冒險者追尋其蹤跡。"
    },
    {
      "id": 403,
      "level": "五星",
      "name": "冰晶鯨魚",
      "min_size_m": 3.0,
      "max_size_m": 5.0,
      "min_weight_kg": 3000.0,
      "max_weight_kg": 10000.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "棲息於極寒海域的神秘巨鯨，呼出的氣息在空中凝結成璀璨冰花。據說月光映照的夜晚，背上冰晶會折射出夢幻極光，為迷航的船隻指引方向。"
    },
    {
      "id": 404,
      "level": "五星",
      "name": "藍屏死神鯊",
      "min_size_m": 1.0,
      "max_size_m": 2.0,
      "min_weight_kg": 10.0,
      "max_weight_kg": 20.0,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "X9vK2#mP7@qL$8Nz!4Rw&cY1*TfD6^uJ3%HsA0BgE5a8Z#Qw2$Lm9!Xp4&Vr7^Kt1@ Nc5%Hy3*Df0Bg6Js8Pw2Rn#Uk9"
    },
    {
      "id": 405,
      "level": "五星",
      "name": "珍珠奶茶魚",
      "min_size_m": 0.5,
      "max_size_m": 1.0,
      "min_weight_kg": 0.5,
      "max_weight_kg": 1.5,
      "is_unlocked": False,
      "max_weight": 0.0,
      "catch_count": 0,
      "comment": "台灣海域特有種，大杯奶茶全糖少冰，比你還有種"
    }
  ]
}

def get_fish_data(fish_id):
    for fish in FISH_MASTER_DATA["fish_list"]:
        if fish["id"] == fish_id:
            return fish 
    return None